### ISSUE TITLE
Support for custom instance names and context url's

### ISSUE THREAD

**Issue by chasinglogic** [praelatus/frontend#134]
We need to figure out how to support this, i.e. should this be an endpoint? (Seems weird) or should we inject some javascript into the index.html from the backend. (seems mildly gross)

**Comment by lionize** [comment]
The best way to handle this will likely be server rendering of some
Javascript stuff. It's not as gross and unheard of as you'd think, but I
have zero experience with it so it'll take some investigation. It'll end up
being something we want to investigate anyway though as it's a common way
to cut down on initial page load times too, so it's a good road to go down.

**Comment by chasinglogic** [comment]
My recommendation would go back to what I said before, we should make the frontend a simple go package and just let me import it, then I can do a template for your index.html

**Comment by lionize** [comment]
What does it mean to do a template?

**Comment by chasinglogic** [comment]
Go has templating support, just like `.erb` or `.eex` templates though the filename doesn't matter.

**Comment by chasinglogic** [comment]
Your index.html would look like this:

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
  <title>Praelatus</title>
  <script>
   const instanceName = {{ .InstanceName }}
   const contextURL = {{ .ContextURL }}
  </script>
</head>
<body>
  <div id="root"></div>
  <script src="/static/index.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
</body>
</html>
```

**Comment by chasinglogic** [comment]
And I could throw a little go file in the root of the repo that would render that and throw it into my code.

**Comment by lionize** [comment]
I don't know enough about React server rendering to know if that'd work or not. I'll come back to this.

**Comment by chasinglogic** [comment]
I wasn't planning on using React server side rendering, I was planning on using golang stdlib, for react server side rendering there's this https://github.com/olebedev/go-starter-kit which uses goja (a javascript engine written in go) but that seems like a lot of hulabaloo for little gain when this works.

**Comment by chasinglogic** [comment]
If we were doing server side rendering with React elsewhere that could make sense but I bet goja slows everything down since the entire thing will get compiled into our binary

**Comment by chasinglogic** [comment]
Looking at the underlying goja (which we'd use to render the JS) we can pass values to JS from Go using it but according the readme it's pretty slow and a memory hog https://github.com/dop251/goja

I'd rather do it my way since it's faster. With goja that's a big dependency for this one thing. There are other versions using otto which are a bit simpler but they're even slower.
